# Generated by Django 3.2.7 on 2021-11-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='details',
            new_name='description',
        ),
        migrations.AddField(
            model_name='contact',
            name='Collegename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='usn',
            field=models.CharField(default='', max_length=10),
        ),
    ]
